[project]
name = "browser-use-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "browser-use>=0.1.37",
    "langchain-google-genai>=2.0.8",
]
